/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.4_@types+n_36dvb4ieu3rramgpoff5rdxgbu/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.4_@types+n_36dvb4ieu3rramgpoff5rdxgbu/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    ULinkBase: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.4_@types+n_36dvb4ieu3rramgpoff5rdxgbu/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
  }
}
